interface DefaultLangType {
  VALIDATOR_ERROR: string,
  MALFORMED_JSON_REQUEST_BODY: string,
  INTERNAL_SERVER_ERROR: string,
  BAD_REQUEST: string,
  SUCCESS: string,
  CREATED: string,
  UNAUTHORIZED: string,
  INVALID_OR_EXPIRED_TOKEN: string,
  PERMISSION_DENIED: string,
}
const DefaultLangs: DefaultLangType = {
  VALIDATOR_ERROR: 'VALIDATOR_ERROR',
  MALFORMED_JSON_REQUEST_BODY: 'MALFORMED_JSON_REQUEST_BODY',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  BAD_REQUEST: 'BAD_REQUEST',
  SUCCESS: 'SUCCESS',
  CREATED: 'CREATED',
  UNAUTHORIZED: 'UNAUTHORIZED',
  INVALID_OR_EXPIRED_TOKEN: 'INVALID_OR_EXPIRED_TOKEN',
  PERMISSION_DENIED: 'PERMISSION_DENIED',
};

export default DefaultLangs;